### ISSUE TITLE
Empty topic when using the plugin

### ISSUE THREAD

**Issue by stefan-jung** [oxygenxml/dita-ot-diagrams-plugin#15]
When I use this given Mermaid sample:

```xml
<foreign outputclass="embed-mermaid-diagram">
    graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
</foreign>
```

The webhelp topic containing this code is not rendered at all. The HTML file is completely empty. All other topics are rendered fine. The DITA-OT does not throw an error message.

The Plant UML diagrams (which are generated locally) work fine. So I guess the DITA-OT cannot contact the Mermaid server. IMHO the build should throw an ERROR in this case.

**Comment by jlacour31** [comment]
@stefan-jung I tried the plugin in Oxygen Publishing Engine 27.0 and the diagram did render in WebHelp Responsive output:

![image](https://github.com/user-attachments/assets/4a726d55-459f-4fc5-8f59-880487a48092)

**Comment by stefan-jung** [comment]
@jlacour31 Does it also render when you disconnect all network connections (the Mermaid API is not reachable)?

**Comment by jlacour31** [comment]
@stefan-jung I did some modifications could you try to update the plugin and see if you get a warning now?
I don't think an error is necessary in this case, the diagram will be ignored and the output will contains the topic.
