### ISSUE TITLE
Bidirectional arrow (<-->) results in "The content of elements must consist of well-formed character data or markup".

### ISSUE THREAD

**Issue by DivyaRao23** [oxygenxml/dita-ot-diagrams-plugin#3]
I have an XSLT that converts these bidirectional arrows into &lt;--&gt;. Using the encoding I can skip the XML parsing error. However, with encoded &lt;--&gt; the HTML transformation fails to the render SVG image. 

If I use unidirectional arrow, it works. ( afsvm--&gt;afs)

Excerpt Dita file
---------------------
         <foreign outputclass="embed-plant-uml"> 
            @startuml 
            left to right direction
            agent apc as "PC"
            agent afsvm as "VM"
            agent afs as "FS"
            apc--&gt;afsvm 
            afsvm&lt;--&gt;afs
            @enduml </foreign>

**Comment by raducoravu** [comment]
@DivyaRao23 can you try to re-download and re-install the plugin? I made a change to the "extensions.jar" library.
In addition I think you also need to install this extra application: https://plantuml.com/graphviz-dot to have the PlantUML libraries properly be able to create your diagram.

**Comment by DivyaRao23** [comment]
@raducoravu, Thank you for the reply.

1. I downloaded the latest plugin and reinstalled (I did use, dita --install to reinstall after copying the plugin). Still observe the same error.
-----------------------------------------------------
     [xslt] Error evaluating (fn:parse-xml(...)) in xsl:copy-of/@select on line 21 column 141 of xhtmlSVG.xsl:
     [xslt]   FODC0006: First argument to parse-xml() is not a well-formed and namespace-well-formed XML
     [xslt]   document. XML parser reported: org.xml.sax.SAXParseException; systemId:
     [xslt]   file:/dita-ot-3.6.1/plugins/com.oxygenxml.diagrams.svg/xsl/xhtmlSVG.xsl; lineNumber: 30; columnNumber: 26; The content of elements must consist of well-formed character data or markup.
-----------------------------------------------------
   
2. I have the following version of Dot installed.

--------------------------------------------
java -jar plantuml.jar -testdot                         
The environment variable GRAPHVIZ_DOT has been set to /usr/local/bin/dot
Dot executable is /usr/local/bin/dot
Dot version: dot - graphviz version 2.49.0 (20210828.1703)
Installation seems OK. File generation OK
-----------------------------------------------

**Comment by raducoravu** [comment]
I'm testing on my side publishing this sample project with the latest plugin installed in DITA OT 3.7 to HTML5 output:
[flowers.zip](https://github.com/oxygenxml/dita-ot-diagrams-plugin/files/8213608/flowers.zip)
and I do not get that SAXParseException error reported in the console.
Can you also try with my small sample project? If you cannot reproduce the problem with it, maybe it's another situation and you need to give me a small DITA project to test on my side.
If you reproduce the problem also with my sample, this might mean that you may have not updated the plugin's contents.

**Comment by DivyaRao23** [comment]
I'm using dita-ot-3.6.1 and my Java version: 17.
With the flowers project, I do not get any SAXParseException error reported in the console. However, the SVG image doesn't render completely. 
![image](https://user-images.githubusercontent.com/82793275/157424450-a3c080e5-c6d4-4f76-b5d4-b3dd89136e52.png)
[flowers-html5.zip](https://github.com/oxygenxml/dita-ot-diagrams-plugin/files/8213852/flowers-html5.zip)

**Comment by raducoravu** [comment]
@DivyaRao23 I think I made this work, maybe you can re-download the plugin and try again.

**Comment by DivyaRao23** [comment]
@raducoravu , I downloaded the plugin again and reinstalled. It is now working. Thank you so much for the help.

**Comment by raducoravu** [comment]
@DivyaRao23 I'm glad I could help.
